// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miner.proto

package blockchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendAddressRequest struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAddressRequest) Reset()         { *m = SendAddressRequest{} }
func (m *SendAddressRequest) String() string { return proto.CompactTextString(m) }
func (*SendAddressRequest) ProtoMessage()    {}
func (*SendAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{0}
}

func (m *SendAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAddressRequest.Unmarshal(m, b)
}
func (m *SendAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAddressRequest.Marshal(b, m, deterministic)
}
func (m *SendAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAddressRequest.Merge(m, src)
}
func (m *SendAddressRequest) XXX_Size() int {
	return xxx_messageInfo_SendAddressRequest.Size(m)
}
func (m *SendAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendAddressRequest proto.InternalMessageInfo

func (m *SendAddressRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SendAddressResponse struct {
	ResponseText         string   `protobuf:"bytes,1,opt,name=responseText,proto3" json:"responseText,omitempty"`
	StatusCode           uint64   `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAddressResponse) Reset()         { *m = SendAddressResponse{} }
func (m *SendAddressResponse) String() string { return proto.CompactTextString(m) }
func (*SendAddressResponse) ProtoMessage()    {}
func (*SendAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{1}
}

func (m *SendAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAddressResponse.Unmarshal(m, b)
}
func (m *SendAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAddressResponse.Marshal(b, m, deterministic)
}
func (m *SendAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAddressResponse.Merge(m, src)
}
func (m *SendAddressResponse) XXX_Size() int {
	return xxx_messageInfo_SendAddressResponse.Size(m)
}
func (m *SendAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendAddressResponse proto.InternalMessageInfo

func (m *SendAddressResponse) GetResponseText() string {
	if m != nil {
		return m.ResponseText
	}
	return ""
}

func (m *SendAddressResponse) GetStatusCode() uint64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type GetAddressRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressRequest) Reset()         { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()    {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{2}
}

func (m *GetAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressRequest.Unmarshal(m, b)
}
func (m *GetAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressRequest.Merge(m, src)
}
func (m *GetAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddressRequest.Size(m)
}
func (m *GetAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressRequest proto.InternalMessageInfo

type GetAddressResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressResponse) Reset()         { *m = GetAddressResponse{} }
func (m *GetAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetAddressResponse) ProtoMessage()    {}
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{3}
}

func (m *GetAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressResponse.Unmarshal(m, b)
}
func (m *GetAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressResponse.Merge(m, src)
}
func (m *GetAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetAddressResponse.Size(m)
}
func (m *GetAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressResponse proto.InternalMessageInfo

func (m *GetAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type FullHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullHeightRequest) Reset()         { *m = FullHeightRequest{} }
func (m *FullHeightRequest) String() string { return proto.CompactTextString(m) }
func (*FullHeightRequest) ProtoMessage()    {}
func (*FullHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{4}
}

func (m *FullHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullHeightRequest.Unmarshal(m, b)
}
func (m *FullHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullHeightRequest.Marshal(b, m, deterministic)
}
func (m *FullHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullHeightRequest.Merge(m, src)
}
func (m *FullHeightRequest) XXX_Size() int {
	return xxx_messageInfo_FullHeightRequest.Size(m)
}
func (m *FullHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FullHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FullHeightRequest proto.InternalMessageInfo

func (m *FullHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type FullHeightResponse struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullHeightResponse) Reset()         { *m = FullHeightResponse{} }
func (m *FullHeightResponse) String() string { return proto.CompactTextString(m) }
func (*FullHeightResponse) ProtoMessage()    {}
func (*FullHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{5}
}

func (m *FullHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullHeightResponse.Unmarshal(m, b)
}
func (m *FullHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullHeightResponse.Marshal(b, m, deterministic)
}
func (m *FullHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullHeightResponse.Merge(m, src)
}
func (m *FullHeightResponse) XXX_Size() int {
	return xxx_messageInfo_FullHeightResponse.Size(m)
}
func (m *FullHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FullHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FullHeightResponse proto.InternalMessageInfo

func (m *FullHeightResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetFullChainRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFullChainRequest) Reset()         { *m = GetFullChainRequest{} }
func (m *GetFullChainRequest) String() string { return proto.CompactTextString(m) }
func (*GetFullChainRequest) ProtoMessage()    {}
func (*GetFullChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{6}
}

func (m *GetFullChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFullChainRequest.Unmarshal(m, b)
}
func (m *GetFullChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFullChainRequest.Marshal(b, m, deterministic)
}
func (m *GetFullChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFullChainRequest.Merge(m, src)
}
func (m *GetFullChainRequest) XXX_Size() int {
	return xxx_messageInfo_GetFullChainRequest.Size(m)
}
func (m *GetFullChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFullChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFullChainRequest proto.InternalMessageInfo

type GetFullChainResponse struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFullChainResponse) Reset()         { *m = GetFullChainResponse{} }
func (m *GetFullChainResponse) String() string { return proto.CompactTextString(m) }
func (*GetFullChainResponse) ProtoMessage()    {}
func (*GetFullChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{7}
}

func (m *GetFullChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFullChainResponse.Unmarshal(m, b)
}
func (m *GetFullChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFullChainResponse.Marshal(b, m, deterministic)
}
func (m *GetFullChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFullChainResponse.Merge(m, src)
}
func (m *GetFullChainResponse) XXX_Size() int {
	return xxx_messageInfo_GetFullChainResponse.Size(m)
}
func (m *GetFullChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFullChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFullChainResponse proto.InternalMessageInfo

func (m *GetFullChainResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetFullChainResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PropagateBlockRequest struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateBlockRequest) Reset()         { *m = PropagateBlockRequest{} }
func (m *PropagateBlockRequest) String() string { return proto.CompactTextString(m) }
func (*PropagateBlockRequest) ProtoMessage()    {}
func (*PropagateBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{8}
}

func (m *PropagateBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateBlockRequest.Unmarshal(m, b)
}
func (m *PropagateBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateBlockRequest.Marshal(b, m, deterministic)
}
func (m *PropagateBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateBlockRequest.Merge(m, src)
}
func (m *PropagateBlockRequest) XXX_Size() int {
	return xxx_messageInfo_PropagateBlockRequest.Size(m)
}
func (m *PropagateBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateBlockRequest proto.InternalMessageInfo

func (m *PropagateBlockRequest) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type PropagateBlockResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateBlockResponse) Reset()         { *m = PropagateBlockResponse{} }
func (m *PropagateBlockResponse) String() string { return proto.CompactTextString(m) }
func (*PropagateBlockResponse) ProtoMessage()    {}
func (*PropagateBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{9}
}

func (m *PropagateBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateBlockResponse.Unmarshal(m, b)
}
func (m *PropagateBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateBlockResponse.Marshal(b, m, deterministic)
}
func (m *PropagateBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateBlockResponse.Merge(m, src)
}
func (m *PropagateBlockResponse) XXX_Size() int {
	return xxx_messageInfo_PropagateBlockResponse.Size(m)
}
func (m *PropagateBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateBlockResponse proto.InternalMessageInfo

func (m *PropagateBlockResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type TokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{10}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TokenResponse struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{11}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{12}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{13}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type HeightRequest struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeightRequest) Reset()         { *m = HeightRequest{} }
func (m *HeightRequest) String() string { return proto.CompactTextString(m) }
func (*HeightRequest) ProtoMessage()    {}
func (*HeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{14}
}

func (m *HeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeightRequest.Unmarshal(m, b)
}
func (m *HeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeightRequest.Marshal(b, m, deterministic)
}
func (m *HeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeightRequest.Merge(m, src)
}
func (m *HeightRequest) XXX_Size() int {
	return xxx_messageInfo_HeightRequest.Size(m)
}
func (m *HeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeightRequest proto.InternalMessageInfo

func (m *HeightRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type HeightResponse struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeightResponse) Reset()         { *m = HeightResponse{} }
func (m *HeightResponse) String() string { return proto.CompactTextString(m) }
func (*HeightResponse) ProtoMessage()    {}
func (*HeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{15}
}

func (m *HeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeightResponse.Unmarshal(m, b)
}
func (m *HeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeightResponse.Marshal(b, m, deterministic)
}
func (m *HeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeightResponse.Merge(m, src)
}
func (m *HeightResponse) XXX_Size() int {
	return xxx_messageInfo_HeightResponse.Size(m)
}
func (m *HeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeightResponse proto.InternalMessageInfo

func (m *HeightResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetChainRequest struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainRequest) Reset()         { *m = GetChainRequest{} }
func (m *GetChainRequest) String() string { return proto.CompactTextString(m) }
func (*GetChainRequest) ProtoMessage()    {}
func (*GetChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{16}
}

func (m *GetChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainRequest.Unmarshal(m, b)
}
func (m *GetChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainRequest.Marshal(b, m, deterministic)
}
func (m *GetChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainRequest.Merge(m, src)
}
func (m *GetChainRequest) XXX_Size() int {
	return xxx_messageInfo_GetChainRequest.Size(m)
}
func (m *GetChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainRequest proto.InternalMessageInfo

func (m *GetChainRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetChainResponse struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainResponse) Reset()         { *m = GetChainResponse{} }
func (m *GetChainResponse) String() string { return proto.CompactTextString(m) }
func (*GetChainResponse) ProtoMessage()    {}
func (*GetChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{17}
}

func (m *GetChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainResponse.Unmarshal(m, b)
}
func (m *GetChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainResponse.Marshal(b, m, deterministic)
}
func (m *GetChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainResponse.Merge(m, src)
}
func (m *GetChainResponse) XXX_Size() int {
	return xxx_messageInfo_GetChainResponse.Size(m)
}
func (m *GetChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainResponse proto.InternalMessageInfo

func (m *GetChainResponse) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type MineRequest struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MineRequest) Reset()         { *m = MineRequest{} }
func (m *MineRequest) String() string { return proto.CompactTextString(m) }
func (*MineRequest) ProtoMessage()    {}
func (*MineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{18}
}

func (m *MineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MineRequest.Unmarshal(m, b)
}
func (m *MineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MineRequest.Marshal(b, m, deterministic)
}
func (m *MineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MineRequest.Merge(m, src)
}
func (m *MineRequest) XXX_Size() int {
	return xxx_messageInfo_MineRequest.Size(m)
}
func (m *MineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MineRequest proto.InternalMessageInfo

func (m *MineRequest) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type MineResponse struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MineResponse) Reset()         { *m = MineResponse{} }
func (m *MineResponse) String() string { return proto.CompactTextString(m) }
func (*MineResponse) ProtoMessage()    {}
func (*MineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{19}
}

func (m *MineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MineResponse.Unmarshal(m, b)
}
func (m *MineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MineResponse.Marshal(b, m, deterministic)
}
func (m *MineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MineResponse.Merge(m, src)
}
func (m *MineResponse) XXX_Size() int {
	return xxx_messageInfo_MineResponse.Size(m)
}
func (m *MineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MineResponse proto.InternalMessageInfo

func (m *MineResponse) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type TestRequest struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{20}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type TestResponse struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e7fcaacee94c057, []int{21}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*SendAddressRequest)(nil), "blockchain.SendAddressRequest")
	proto.RegisterType((*SendAddressResponse)(nil), "blockchain.SendAddressResponse")
	proto.RegisterType((*GetAddressRequest)(nil), "blockchain.GetAddressRequest")
	proto.RegisterType((*GetAddressResponse)(nil), "blockchain.GetAddressResponse")
	proto.RegisterType((*FullHeightRequest)(nil), "blockchain.FullHeightRequest")
	proto.RegisterType((*FullHeightResponse)(nil), "blockchain.FullHeightResponse")
	proto.RegisterType((*GetFullChainRequest)(nil), "blockchain.GetFullChainRequest")
	proto.RegisterType((*GetFullChainResponse)(nil), "blockchain.GetFullChainResponse")
	proto.RegisterType((*PropagateBlockRequest)(nil), "blockchain.PropagateBlockRequest")
	proto.RegisterType((*PropagateBlockResponse)(nil), "blockchain.PropagateBlockResponse")
	proto.RegisterType((*TokenRequest)(nil), "blockchain.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "blockchain.TokenResponse")
	proto.RegisterType((*PingRequest)(nil), "blockchain.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "blockchain.PingResponse")
	proto.RegisterType((*HeightRequest)(nil), "blockchain.HeightRequest")
	proto.RegisterType((*HeightResponse)(nil), "blockchain.HeightResponse")
	proto.RegisterType((*GetChainRequest)(nil), "blockchain.GetChainRequest")
	proto.RegisterType((*GetChainResponse)(nil), "blockchain.GetChainResponse")
	proto.RegisterType((*MineRequest)(nil), "blockchain.MineRequest")
	proto.RegisterType((*MineResponse)(nil), "blockchain.MineResponse")
	proto.RegisterType((*TestRequest)(nil), "blockchain.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "blockchain.TestResponse")
}

func init() { proto.RegisterFile("miner.proto", fileDescriptor_6e7fcaacee94c057) }

var fileDescriptor_6e7fcaacee94c057 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xef, 0x6f, 0x12, 0x41,
	0x10, 0x0d, 0x14, 0x90, 0x3e, 0xae, 0xd8, 0x2e, 0xb4, 0xd2, 0x53, 0x29, 0xae, 0x1a, 0x49, 0x54,
	0x62, 0xf4, 0x13, 0x89, 0xd1, 0x68, 0x93, 0x62, 0x62, 0x6a, 0x9a, 0x2b, 0x89, 0xf1, 0xe3, 0xb5,
	0xb7, 0x01, 0x02, 0xbd, 0xc3, 0xdb, 0xc5, 0x1f, 0xff, 0x8a, 0x7f, 0xad, 0xd9, 0xdb, 0x3d, 0x6e,
	0x17, 0x0e, 0xda, 0x6f, 0x37, 0x33, 0x6f, 0xde, 0xbc, 0x9d, 0xe1, 0x05, 0xd4, 0x6e, 0x26, 0x21,
	0x8b, 0x7b, 0xf3, 0x38, 0x12, 0x11, 0xc1, 0xd5, 0x2c, 0xba, 0x9e, 0x5e, 0x8f, 0xfd, 0x49, 0x48,
	0xbb, 0x20, 0x97, 0x2c, 0x0c, 0x3e, 0x05, 0x41, 0xcc, 0x38, 0xf7, 0xd8, 0xcf, 0x05, 0xe3, 0x82,
	0x10, 0x94, 0xfc, 0x20, 0x88, 0x5b, 0x85, 0x4e, 0xa1, 0xbb, 0xeb, 0x25, 0xdf, 0xf4, 0x07, 0x1a,
	0x16, 0x92, 0xcf, 0xa3, 0x90, 0x33, 0x42, 0xe1, 0xc4, 0xfa, 0x7b, 0xc8, 0xfe, 0x08, 0xdd, 0x62,
	0xe5, 0x48, 0x1b, 0xe0, 0xc2, 0x17, 0x0b, 0x7e, 0x1a, 0x05, 0xac, 0x55, 0xec, 0x14, 0xba, 0x25,
	0xcf, 0xc8, 0xd0, 0x06, 0x0e, 0x06, 0x4c, 0xd8, 0x1a, 0x68, 0x0f, 0xc4, 0x4c, 0xea, 0x71, 0x2d,
	0xdc, 0xf3, 0x55, 0x4a, 0x4f, 0x4a, 0x43, 0xfa, 0x12, 0x07, 0x67, 0x8b, 0xd9, 0xec, 0x0b, 0x9b,
	0x8c, 0xc6, 0x22, 0x7d, 0xc8, 0x11, 0x2a, 0xe3, 0x24, 0x91, 0xa0, 0x77, 0x3c, 0x1d, 0xd1, 0x57,
	0x20, 0x26, 0x58, 0x93, 0x6f, 0x42, 0x1f, 0xa2, 0x31, 0x60, 0x42, 0x36, 0x9c, 0xca, 0xa5, 0xa5,
	0x0a, 0x3f, 0xa0, 0x69, 0xa7, 0x35, 0xcd, 0x3e, 0x76, 0xa6, 0xec, 0x6f, 0xc2, 0xe1, 0x78, 0xf2,
	0x93, 0x34, 0x51, 0xfe, 0xe5, 0xcf, 0x16, 0xea, 0xed, 0x8e, 0xa7, 0x02, 0xfa, 0x1a, 0x87, 0x17,
	0x71, 0x34, 0xf7, 0x47, 0xbe, 0x60, 0x9f, 0xe5, 0x49, 0x52, 0xd5, 0x4d, 0x94, 0x93, 0x13, 0x69,
	0x0a, 0x15, 0xd0, 0x2e, 0x8e, 0x56, 0xe1, 0x7a, 0x60, 0x1d, 0xc5, 0x48, 0x81, 0xab, 0x5e, 0x31,
	0x9a, 0xd2, 0x33, 0x38, 0xc3, 0x68, 0xca, 0x52, 0xa1, 0xc4, 0x45, 0x75, 0xc1, 0x59, 0x1c, 0xfa,
	0x37, 0x4c, 0x6f, 0x6d, 0x19, 0xcb, 0xda, 0xdc, 0xe7, 0xfc, 0x77, 0x14, 0x07, 0x89, 0xba, 0x5d,
	0x6f, 0x19, 0xd3, 0xe7, 0xd8, 0xd3, 0x3c, 0x7a, 0x50, 0x13, 0x65, 0x21, 0x13, 0xa9, 0xb0, 0x24,
	0xa0, 0x7b, 0xa8, 0x5d, 0x4c, 0xc2, 0x51, 0xba, 0x96, 0x3a, 0x1c, 0x15, 0xaa, 0x26, 0xc9, 0x62,
	0x1f, 0x25, 0x9f, 0xa5, 0x8b, 0xfa, 0x1d, 0xcf, 0xf1, 0x02, 0xf7, 0x07, 0x4c, 0x98, 0xa7, 0xd8,
	0x48, 0xb9, 0x9f, 0x01, 0xb3, 0x27, 0xe4, 0xec, 0xf6, 0x29, 0x6a, 0xe7, 0x93, 0x90, 0x6d, 0x3f,
	0xc0, 0x33, 0x38, 0x0a, 0x74, 0x1b, 0xd5, 0x90, 0x71, 0x71, 0x2b, 0x95, 0x02, 0x6d, 0xa3, 0x7a,
	0xfb, 0xaf, 0x82, 0xb2, 0x9c, 0x18, 0x93, 0x6f, 0xa8, 0x19, 0xe6, 0x23, 0xed, 0x5e, 0x66, 0xe1,
	0xde, 0xba, 0x7f, 0xdd, 0x93, 0x8d, 0x75, 0x3d, 0xef, 0x1c, 0xc8, 0xcc, 0x45, 0x1e, 0x9b, 0xf0,
	0x35, 0x27, 0xba, 0xed, 0x4d, 0x65, 0x45, 0xf6, 0xa6, 0x40, 0xbe, 0x02, 0x99, 0x9d, 0x6c, 0xba,
	0x35, 0x4f, 0xda, 0x74, 0x39, 0x2e, 0xfc, 0x88, 0x8a, 0x26, 0x3a, 0x36, 0x91, 0x36, 0x89, 0x9b,
	0x57, 0xd2, 0x04, 0x97, 0x70, 0x4c, 0x5f, 0x92, 0x93, 0x15, 0xfd, 0xab, 0x46, 0x76, 0x3b, 0x9b,
	0x01, 0xcb, 0x27, 0x7e, 0x47, 0xdd, 0x76, 0x1f, 0x79, 0x62, 0x76, 0xe5, 0x1a, 0xd9, 0xa5, 0xdb,
	0x20, 0x5a, 0xed, 0x7b, 0x94, 0x13, 0x93, 0x91, 0x96, 0x09, 0x36, 0xfd, 0xeb, 0x1e, 0xe7, 0x54,
	0x74, 0x77, 0x1f, 0x25, 0x69, 0x36, 0xf2, 0xc0, 0x9a, 0x94, 0xb9, 0xd1, 0x6d, 0xad, 0x17, 0x74,
	0xeb, 0x00, 0xd5, 0xd4, 0x1d, 0xe4, 0xe1, 0xca, 0x06, 0xac, 0xf5, 0x3c, 0xca, 0x2f, 0x2e, 0x57,
	0xd3, 0x47, 0x49, 0xfe, 0x4a, 0x6d, 0x0d, 0x86, 0x9d, 0x6c, 0x0d, 0x96, 0x85, 0xfa, 0x28, 0x49,
	0x1f, 0xd8, 0xad, 0x86, 0x7d, 0xec, 0x56, 0xd3, 0x32, 0x57, 0x95, 0xe4, 0xcf, 0xec, 0xdd, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x47, 0x8c, 0xdb, 0xdb, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MinerClient is the client API for Miner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinerClient interface {
	SendAddress(ctx context.Context, in *SendAddressRequest, opts ...grpc.CallOption) (*SendAddressResponse, error)
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (Miner_GetAddressClient, error)
	FullHeight(ctx context.Context, in *FullHeightRequest, opts ...grpc.CallOption) (*FullHeightResponse, error)
	Height(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*HeightResponse, error)
	GetFullChain(ctx context.Context, in *GetFullChainRequest, opts ...grpc.CallOption) (Miner_GetFullChainClient, error)
	PropagateBlock(ctx context.Context, in *PropagateBlockRequest, opts ...grpc.CallOption) (*PropagateBlockResponse, error)
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetChain(ctx context.Context, in *GetChainRequest, opts ...grpc.CallOption) (Miner_GetChainClient, error)
	Mine(ctx context.Context, in *MineRequest, opts ...grpc.CallOption) (*MineResponse, error)
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type minerClient struct {
	cc grpc.ClientConnInterface
}

func NewMinerClient(cc grpc.ClientConnInterface) MinerClient {
	return &minerClient{cc}
}

func (c *minerClient) SendAddress(ctx context.Context, in *SendAddressRequest, opts ...grpc.CallOption) (*SendAddressResponse, error) {
	out := new(SendAddressResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/SendAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (Miner_GetAddressClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Miner_serviceDesc.Streams[0], "/blockchain.Miner/GetAddress", opts...)
	if err != nil {
		return nil, err
	}
	x := &minerGetAddressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Miner_GetAddressClient interface {
	Recv() (*GetAddressResponse, error)
	grpc.ClientStream
}

type minerGetAddressClient struct {
	grpc.ClientStream
}

func (x *minerGetAddressClient) Recv() (*GetAddressResponse, error) {
	m := new(GetAddressResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *minerClient) FullHeight(ctx context.Context, in *FullHeightRequest, opts ...grpc.CallOption) (*FullHeightResponse, error) {
	out := new(FullHeightResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/FullHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Height(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*HeightResponse, error) {
	out := new(HeightResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/Height", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) GetFullChain(ctx context.Context, in *GetFullChainRequest, opts ...grpc.CallOption) (Miner_GetFullChainClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Miner_serviceDesc.Streams[1], "/blockchain.Miner/GetFullChain", opts...)
	if err != nil {
		return nil, err
	}
	x := &minerGetFullChainClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Miner_GetFullChainClient interface {
	Recv() (*GetFullChainResponse, error)
	grpc.ClientStream
}

type minerGetFullChainClient struct {
	grpc.ClientStream
}

func (x *minerGetFullChainClient) Recv() (*GetFullChainResponse, error) {
	m := new(GetFullChainResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *minerClient) PropagateBlock(ctx context.Context, in *PropagateBlockRequest, opts ...grpc.CallOption) (*PropagateBlockResponse, error) {
	out := new(PropagateBlockResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/PropagateBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) GetChain(ctx context.Context, in *GetChainRequest, opts ...grpc.CallOption) (Miner_GetChainClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Miner_serviceDesc.Streams[2], "/blockchain.Miner/GetChain", opts...)
	if err != nil {
		return nil, err
	}
	x := &minerGetChainClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Miner_GetChainClient interface {
	Recv() (*GetChainResponse, error)
	grpc.ClientStream
}

type minerGetChainClient struct {
	grpc.ClientStream
}

func (x *minerGetChainClient) Recv() (*GetChainResponse, error) {
	m := new(GetChainResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *minerClient) Mine(ctx context.Context, in *MineRequest, opts ...grpc.CallOption) (*MineResponse, error) {
	out := new(MineResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/Mine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Miner/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinerServer is the server API for Miner service.
type MinerServer interface {
	SendAddress(context.Context, *SendAddressRequest) (*SendAddressResponse, error)
	GetAddress(*GetAddressRequest, Miner_GetAddressServer) error
	FullHeight(context.Context, *FullHeightRequest) (*FullHeightResponse, error)
	Height(context.Context, *HeightRequest) (*HeightResponse, error)
	GetFullChain(*GetFullChainRequest, Miner_GetFullChainServer) error
	PropagateBlock(context.Context, *PropagateBlockRequest) (*PropagateBlockResponse, error)
	Token(context.Context, *TokenRequest) (*TokenResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetChain(*GetChainRequest, Miner_GetChainServer) error
	Mine(context.Context, *MineRequest) (*MineResponse, error)
	Test(context.Context, *TestRequest) (*TestResponse, error)
}

// UnimplementedMinerServer can be embedded to have forward compatible implementations.
type UnimplementedMinerServer struct {
}

func (*UnimplementedMinerServer) SendAddress(ctx context.Context, req *SendAddressRequest) (*SendAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAddress not implemented")
}
func (*UnimplementedMinerServer) GetAddress(req *GetAddressRequest, srv Miner_GetAddressServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (*UnimplementedMinerServer) FullHeight(ctx context.Context, req *FullHeightRequest) (*FullHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FullHeight not implemented")
}
func (*UnimplementedMinerServer) Height(ctx context.Context, req *HeightRequest) (*HeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Height not implemented")
}
func (*UnimplementedMinerServer) GetFullChain(req *GetFullChainRequest, srv Miner_GetFullChainServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFullChain not implemented")
}
func (*UnimplementedMinerServer) PropagateBlock(ctx context.Context, req *PropagateBlockRequest) (*PropagateBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PropagateBlock not implemented")
}
func (*UnimplementedMinerServer) Token(ctx context.Context, req *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (*UnimplementedMinerServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMinerServer) GetChain(req *GetChainRequest, srv Miner_GetChainServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChain not implemented")
}
func (*UnimplementedMinerServer) Mine(ctx context.Context, req *MineRequest) (*MineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mine not implemented")
}
func (*UnimplementedMinerServer) Test(ctx context.Context, req *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterMinerServer(s *grpc.Server, srv MinerServer) {
	s.RegisterService(&_Miner_serviceDesc, srv)
}

func _Miner_SendAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).SendAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/SendAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).SendAddress(ctx, req.(*SendAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_GetAddress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAddressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinerServer).GetAddress(m, &minerGetAddressServer{stream})
}

type Miner_GetAddressServer interface {
	Send(*GetAddressResponse) error
	grpc.ServerStream
}

type minerGetAddressServer struct {
	grpc.ServerStream
}

func (x *minerGetAddressServer) Send(m *GetAddressResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Miner_FullHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).FullHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/FullHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).FullHeight(ctx, req.(*FullHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Height_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Height(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/Height",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Height(ctx, req.(*HeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_GetFullChain_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFullChainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinerServer).GetFullChain(m, &minerGetFullChainServer{stream})
}

type Miner_GetFullChainServer interface {
	Send(*GetFullChainResponse) error
	grpc.ServerStream
}

type minerGetFullChainServer struct {
	grpc.ServerStream
}

func (x *minerGetFullChainServer) Send(m *GetFullChainResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Miner_PropagateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropagateBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).PropagateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/PropagateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).PropagateBlock(ctx, req.(*PropagateBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_GetChain_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinerServer).GetChain(m, &minerGetChainServer{stream})
}

type Miner_GetChainServer interface {
	Send(*GetChainResponse) error
	grpc.ServerStream
}

type minerGetChainServer struct {
	grpc.ServerStream
}

func (x *minerGetChainServer) Send(m *GetChainResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Miner_Mine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Mine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/Mine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Mine(ctx, req.(*MineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Miner/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Miner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.Miner",
	HandlerType: (*MinerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAddress",
			Handler:    _Miner_SendAddress_Handler,
		},
		{
			MethodName: "FullHeight",
			Handler:    _Miner_FullHeight_Handler,
		},
		{
			MethodName: "Height",
			Handler:    _Miner_Height_Handler,
		},
		{
			MethodName: "PropagateBlock",
			Handler:    _Miner_PropagateBlock_Handler,
		},
		{
			MethodName: "Token",
			Handler:    _Miner_Token_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Miner_Ping_Handler,
		},
		{
			MethodName: "Mine",
			Handler:    _Miner_Mine_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Miner_Test_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAddress",
			Handler:       _Miner_GetAddress_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFullChain",
			Handler:       _Miner_GetFullChain_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChain",
			Handler:       _Miner_GetChain_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "miner.proto",
}
